/* Focus & Mock v1. In-memory session only: no network calls or local-storage access. */
(()=>{'use strict';
const app=document.getElementById('app'),DATA=window.MOCK_DATA,HELP=window.FocusHelp;
const VERSION='focus-1.0';
const BLUEPRINT={'1.1':2,'1.2':2,'1.3':1,'2.1':1,'2.2':5,'3.1':2,'4.1':1,'5.1':1,'5.2':1,'6.1':5,'6.2':2,'7.1':17};
const LO={1:'Key concepts',2:'Guiding principles',3:'Four dimensions',4:'Service value system',5:'Service value chain',6:'Practice purposes and terms',7:'Practices in detail'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=arr=>{const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const B=new Map((DATA?.questions||[]).map(q=>[q.id,q]));
const btn=(s,act,primary=false,attrs='')=>`<button ${attrs} data-act="${act}" class="${primary?'primary':''}">${s}</button>`;
const defaultState=()=>({version:1,count:3,topic:'all',records:{},history:[],current:null});
let P=defaultState(),warning='',timer=null,screen='home',reviewIndices=[],reviewPosition=0;
function save(){return true}
function cancelSpeech(){}
function show(html,focus=true){app.innerHTML=`<p id="save-warning" class="error" role="status" ${warning?'':'hidden'}>${esc(warning)}</p>`+html;if(focus){window.scrollTo(0,0);app.querySelector('h1')?.focus({preventScroll:true})}}
function title(s){return `<h1 class="screen-title" tabindex="-1">${s}</h1>`}
function footer(){return `<p class="notice">Independent ITIL 4 practice, not official PeopleCert questions. No guarantee of equal difficulty or exam success. This session stays open while this page is open. Reloading starts fresh; earlier game saves are not changed. <span>Build ${VERSION}</span></p>`}
function home(){screen='home';const s=P.current;show(`<header class="intro"><span class="kicker">ITIL 4 · FOCUS UPDATE</span>${title('One question.<br>One small block.')}<p class="muted">English questions and explanations.<br>Dutch help is one tap away.</p></header>${s&&!s.done?`<section class="card"><p><b>Paused ${s.mode==='focus'?'focus block':'mock exam'}</b><br>Question ${s.index+1} of ${s.items.length}</p>${btn('Resume','resume',true)}<p class="small">${s.mode==='exam'?'The exam timer continues while you are away.':'No timer. Continue at your own pace; keep this tab open.'}</p></section>`:''}<section class="card"><span class="kicker">FOCUS MODE · NO TIMER</span><h2>Your block size</h2><form id="focus-form"><div class="choices" aria-label="Block-size presets">${[1,3,5,10,20].map(n=>btn(String(n),'preset',false,`type="button" data-count="${n}" aria-pressed="${P.count===n}"`)).join('')}</div><div class="fields"><label for="count">Questions per block · choose any number from 1 to 40<input id="count" name="count" type="number" inputmode="numeric" min="1" max="40" step="1" required value="${P.count}" aria-describedby="count-help"></label><span class="small" id="count-help">3, 5, 7… choose what feels manageable.</span><label for="topic">Topics<select id="topic"><option value="all">All topics, mixed</option><option value="practices">Practices · LO6 + LO7</option>${Object.entries(LO).map(([lo,label])=>`<option value="${lo}">LO${lo} · ${esc(label)}</option>`).join('')}</select></label></div><p class="error" id="form-error" role="alert" hidden></p><button class="primary full" type="submit">Start focus block</button></form><p class="small section-gap">Check each answer, read the explanation and take a break at the end. Short blocks are for learning, not a pass/fail prediction.</p></section><section class="card"><details><summary>Full mock · 40 questions / 60 minutes</summary><p>Uninterrupted timed practice. No tips or explanations before submission. You can change answers and flag questions for review.</p>${btn('Start full mock','start-exam',true)}<p class="small section-gap">Practice pass threshold: 26/40. The same question bank is used; prior exposure can raise your score.</p></details>${s?.done?btn('Review last result','results'):''}</section>${footer()}`);app.querySelector('#topic').value=P.topic;app.querySelector('#focus-form').onsubmit=e=>{e.preventDefault();startFocus()};app.querySelector('#count').oninput=e=>{app.querySelectorAll('[data-count]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.count)===Number(e.target.value))))}}
function poolFor(topic){return [...B.values()].filter(q=>topic==='all'||(topic==='practices'?q.lo===6||q.lo===7:String(q.lo)===topic))}
function focusQuestions(count,topic,records=P.records){const pool=poolFor(topic);if(!Number.isInteger(count)||count<1||count>40)throw Error('Choose a whole number from 1 to 40.');if(count>pool.length)throw Error(`This topic has ${pool.length} questions. Choose ${pool.length} or fewer, or select a broader topic.`);return shuffle(pool).sort((a,b)=>{const x=records[a.id],y=records[b.id];return (Number(x?.attempts)||0)-(Number(y?.attempts)||0)||(Number(x?.seenAt)||0)-(Number(y?.seenAt)||0)}).slice(0,count)}
function paper(){const out=[];for(const [criterion,n]of Object.entries(BLUEPRINT)){const pool=[...B.values()].filter(q=>q.criterion===criterion);if(pool.length<n)throw Error('Not enough questions for criterion '+criterion);out.push(...shuffle(pool).slice(0,n))}return shuffle(out)}
function items(qs){return qs.map(q=>({id:q.id,order:shuffle([0,1,2,3]),choice:null,checked:false,flagged:false}))}
function mayReplace(){return !P.current||P.current.done||confirm('Replace the unfinished session? Previously completed answers and results will be kept while this tab stays open.')}
function startFocus(nextBlock=false){try{const count=nextBlock?P.count:Number(app.querySelector('#count').value),topic=nextBlock?P.topic:app.querySelector('#topic').value;const qs=focusQuestions(count,topic);if(!mayReplace())return;P.count=count;P.topic=topic;P.current={mode:'focus',items:items(qs),index:0,done:false,startedAt:Date.now()};startTimer();renderQuestion()}catch(e){const el=app.querySelector('#form-error');if(el){el.hidden=false;el.textContent=e.message}else{warning=e.message;home()}}}
function startExam(){if(!mayReplace())return;try{P.current={mode:'exam',items:items(paper()),index:0,done:false,startedAt:Date.now(),deadline:Date.now()+3600000};startTimer();renderQuestion()}catch(e){warning=e.message;home()}}
function timeLeft(){return Math.max(0,Math.ceil((P.current?.deadline-Date.now())/1000))}
function fmt(s){return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
function startTimer(){if(timer)clearInterval(timer);timer=null;if(P.current?.mode==='exam'&&!P.current.done){timer=setInterval(tick,1000);tick()}}
function tick(){if(P.current?.mode!=='exam'||P.current.done)return;if(timeLeft()<=0){complete(true);return}const el=document.getElementById('timer');if(el){el.textContent=fmt(timeLeft());el.classList.toggle('urgent',timeLeft()<=300)}}
function ready(){if(P.current?.mode==='exam'&&!P.current.done&&timeLeft()<=0){complete(true);return false}return !!P.current&&!P.current.done}
function highlight(s){return esc(s).replace(/\b(NOT|EXCEPT|BEST|MOST|PRIMARY|MAIN|FIRST|NEXT|TWO)\b/g,'<strong class="operator">$1</strong>')}
function renderQuestion(){if(!ready())return;screen='question';const s=P.current,it=s.items[s.index],q=B.get(it.id),focus=s.mode==='focus';show(`<header class="row"><div><span class="kicker">${focus?'FOCUS BLOCK':'FULL MOCK'}</span><b>Question ${s.index+1} / ${s.items.length}</b><div class="small">${focus?'No timer · one at a time':'Tips appear after submission'}</div></div>${focus?btn('Pause','home'):`<span class="timer ${timeLeft()<=300?'urgent':''}" id="timer" aria-label="Time remaining">${fmt(timeLeft())}</span>`}</header><div class="progress" aria-hidden="true"><span style="width:${s.index/s.items.length*100}%"></span></div><section class="card">${titleQuestion(q)}<div class="options" role="group" aria-label="Answer choices">${it.order.map((idx,pos)=>{const state=it.checked?(idx===0?' good':idx===it.choice?' bad':''):'';return `<button class="option${state}" data-choice="${idx}" aria-pressed="${it.choice===idx}" ${it.checked?'disabled':''}><span class="letter">${'ABCD'[pos]}</span><span>${esc(q.options[idx])}</span></button>`}).join('')}</div>${focus?`<div class="actions">${it.checked?btn(s.index===s.items.length-1?'Finish block':'Next question','next-focus',true):btn('Check answer','check',true,it.choice===null?'disabled':'')}${!it.checked?btn('I do not know','unknown'):''}</div>${it.checked?feedback(it)+`<div class="actions">${btn(s.index===s.items.length-1?'Finish block':'Next question','next-focus',true)}</div>`:''}`:`<div class="actions">${btn('Previous','prev',false,s.index===0?'disabled':'')}${btn(s.index===39?'Review & submit':'Next','next-exam',true)}</div><div class="actions">${btn(it.flagged?'★ Flagged':'☆ Flag for review','flag',false,`aria-pressed="${it.flagged}"`)}${btn('Clear answer','clear',false,it.choice===null?'disabled':'')}</div><details id="nav"><summary>Question navigator · ${s.items.filter(i=>i.choice!==null).length}/40 answered</summary>${navigatorHTML(s)}<p class="small">Blue: answered. Gold border: flagged. Outline: current question.</p></details><div class="actions">${btn('Submit mock','submit')}</div>`}</section>`)}
function titleQuestion(q){return `<h1 tabindex="-1" class="question screen-title" lang="en">${highlight(q.prompt)}</h1>`}
function navigatorHTML(s){return `<div class="navigator">${s.items.map((it,j)=>`<button data-jump="${j}" aria-current="${j===s.index}" class="${it.choice!==null?'answered ':''}${it.flagged?'flagged':''}" aria-label="Question ${j+1}${it.choice!==null?', answered':', unanswered'}${it.flagged?', flagged':''}">${j+1}${it.flagged?'*':''}</button>`).join('')}</div>`}
function feedback(it){const q=B.get(it.id),right=it.choice===0,strategy=HELP.strategy(q),g=HELP.guide(q);return `<section class="feedback ${right?'':'bad'}" id="feedback" tabindex="-1" aria-label="Answer explanation"><span class="kicker">EXPLANATION · ENGLISH</span><h2 class="${right?'correct':'wrong'}">${right?'✓ Correct':'✕ '+(it.choice===null||it.choice===-1?'Not answered':'Not quite')}</h2>${!right?`<p class="wrong"><b>Your answer:</b> ${esc(q.options[it.choice]||'No answer selected')}</p>`:''}<p class="correct"><b>Correct answer:</b> ${esc(q.options[0])}</p><h3>Why this answer fits</h3><p lang="en" id="why-en">${esc(q.why)}</p><div class="tip"><h3>Remember</h3><p lang="en">${esc(q.hook)}</p><details><summary>More help: the distinction + an example</summary><p lang="en">${esc(g.distinction)}</p><h3>A separate example</h3><p lang="en">${esc(g.example)}</p><p lang="en"><b>Ask yourself:</b> ${esc(g.selfCheck)}</p></details></div><details><summary>How to read this type of question</summary><div class="tip" lang="en"><h3>${esc(strategy.title)}</h3><ol>${strategy.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></details><details><summary lang="nl">Nederlandse uitleg</summary><p lang="nl">${esc(q.whyNl)}</p></details><p class="small">LO${q.lo} · ${esc(LO[q.lo])} · ${esc(q.tag)}</p></section>`}
function record(it){const r=P.records[it.id]||{attempts:0,correct:0};P.records[it.id]={attempts:(Number(r.attempts)||0)+1,correct:(Number(r.correct)||0)+Number(it.choice===0),seenAt:Date.now()}}
function check(unknown=false){if(!ready()||P.current.mode!=='focus')return;const it=P.current.items[P.current.index];if(it.checked||(!unknown&&it.choice===null))return;if(unknown)it.choice=-1;it.checked=true;record(it);renderQuestion();const f=app.querySelector('#feedback');f?.scrollIntoView({block:'start',behavior:'auto'});f?.focus({preventScroll:true})}
function nextFocus(){if(!ready()||P.current.mode!=='focus'||!P.current.items[P.current.index].checked)return;if(P.current.index===P.current.items.length-1)complete();else{P.current.index++;renderQuestion()}}
function choice(value){if(!ready())return;const s=P.current,it=s.items[s.index];if(it.checked)return;it.choice=value;app.querySelectorAll('[data-choice]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.choice)===value)));const c=app.querySelector('[data-act="check"]');if(c)c.disabled=false;const clear=app.querySelector('[data-act="clear"]');if(clear)clear.disabled=false;const nav=app.querySelector('#nav');if(nav){nav.querySelector('summary').textContent=`Question navigator · ${s.items.filter(i=>i.choice!==null).length}/40 answered`;nav.querySelector('.navigator').outerHTML=navigatorHTML(s)}}
function complete(timeout=false){const s=P.current;if(!s||s.done)return;if(s.mode==='exam')s.items.forEach(it=>{it.checked=true;record(it)});s.done=true;s.timeout=timeout;s.endedAt=Date.now();P.history.push({mode:s.mode,score:s.items.filter(i=>i.choice===0).length,total:s.items.length,date:s.endedAt});P.history=P.history.slice(-20);if(timer)clearInterval(timer);timer=null;results()}
function submit(){if(!ready())return;const n=P.current.items.filter(i=>i.choice===null).length;if(confirm(n?`Submit with ${n} unanswered question${n===1?'':'s'}? Each unanswered question scores zero.`:'Submit this mock? You cannot change answers afterwards.'))complete()}
function results(){const s=P.current;if(!s?.done){home();return}screen='results';const score=s.items.filter(i=>i.choice===0).length,focus=s.mode==='focus',miss=s.items.filter(i=>i.choice!==0).length;const stats={};for(const it of s.items){const lo=B.get(it.id).lo;stats[lo]??={right:0,total:0};stats[lo].total++;stats[lo].right+=Number(it.choice===0)}show(`<section class="card pause"><span class="kicker">${focus?'BLOCK COMPLETE · TAKE A BREAK':'MOCK COMPLETE'}</span>${title(focus?'That is enough for one block.':score>=26?'Practice threshold reached':'Below the practice threshold')}<div class="score">${score} / ${s.items.length}</div><p>${focus?'No need to rush into another block. Take a short break, then continue when you are ready.':`${Math.round(score/40*100)}% · ${s.timeout?'Time expired.':'Submitted.'} Unanswered questions score zero.`}</p><p class="small">${focus?'This is a learning score, not a prediction of exam success.':'Practice threshold: 26/40. This is an unofficial question bank, not a calibrated predictor of the real exam.'}</p><div class="actions">${btn('Review mistakes','review-wrong',true,miss===0?'disabled':'')}${btn('Review all','review-all')}</div>${focus?`<div class="actions">${btn(`Next ${P.count}-question block`,'next-block',true)}</div>`:''}<div class="actions">${btn('Back to settings','home')}</div><details><summary>Results by topic</summary>${Object.entries(stats).sort((a,b)=>a[1].right/a[1].total-b[1].right/b[1].total).map(([lo,x])=>`<div class="topic"><span>LO${lo} · ${LO[lo]}</span><b>${x.right}/${x.total}</b></div>`).join('')}</details><p class="saved">Block finished. Reloading the page starts a new session.</p></section>${footer()}`)}
function startReview(wrongOnly){const s=P.current;if(!s?.done)return;reviewIndices=s.items.map((it,i)=>i).filter(i=>!wrongOnly||s.items[i].choice!==0);if(!reviewIndices.length){results();return}reviewPosition=0;renderReview()}
function renderReview(){screen='review';const idx=reviewIndices[reviewPosition],it=P.current.items[idx],q=B.get(it.id);show(`<header class="row"><div><span class="kicker">ANSWER REVIEW</span><b>${reviewPosition+1} / ${reviewIndices.length}</b></div>${btn('Results','results')}</header><section class="card">${titleQuestion(q)}${feedback(it)}<div class="actions">${btn('Previous','review-prev',false,reviewPosition===0?'disabled':'')}${btn(reviewPosition===reviewIndices.length-1?'Back to results':'Next explanation','review-next',true)}</div></section>`)}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.choice!==undefined){choice(Number(b.dataset.choice));return}if(b.dataset.jump!==undefined){if(ready()){P.current.index=Number(b.dataset.jump);renderQuestion()}return}const act=b.dataset.act;if(act==='preset'){app.querySelector('#count').value=b.dataset.count;app.querySelector('#count').dispatchEvent(new Event('input'));return}const s=P.current;switch(act){case'home':home();break;case'resume':startTimer();s?.done?results():renderQuestion();break;case'start-exam':startExam();break;case'check':check();break;case'unknown':check(true);break;case'next-focus':nextFocus();break;case'prev':case'next-exam':if(ready()){if(act==='next-exam'&&s.index===39){app.querySelector('#nav').open=true;app.querySelector('#nav').scrollIntoView();break}s.index+=act==='prev'?-1:1;renderQuestion()}break;case'clear':if(ready()){s.items[s.index].choice=null;renderQuestion()}break;case'flag':if(ready()){s.items[s.index].flagged=!s.items[s.index].flagged;renderQuestion()}break;case'submit':submit();break;case'results':results();break;case'next-block':startFocus(true);break;case'review-wrong':startReview(true);break;case'review-all':startReview(false);break;case'review-prev':if(reviewPosition>0){reviewPosition--;renderReview()}break;case'review-next':if(reviewPosition<reviewIndices.length-1){reviewPosition++;renderReview()}else results();break}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});
try{if(!HELP||B.size<40)throw Error('The question bank could not be loaded. Reload this page.');for(const q of B.values())if(q.options?.length!==4||new Set(q.options).size!==4||!q.why||!q.whyNl||!q.hook)throw Error('A question is incomplete. This build needs checking.');window.ITILFocus=Object.freeze({version:VERSION,questionCount:B.size,blueprint:BLUEPRINT,paper:()=>paper().map(q=>q.id),focus:(n,t)=>focusQuestions(n,t).map(q=>q.id)});home();startTimer()}catch(e){show(`<section class="card">${title('Unable to start')}<p class="error">${esc(e.message)}</p><p>Reload this page to try again.</p></section>`)}
})();
