/* Study help, shown only after checking a focus answer or submitting a mock. */
(()=>{'use strict';
const strategies={
 negative:{title:'NOT / EXCEPT: find the exception',steps:['Turn the question into: which option does not belong to the stated definition, purpose or situation? Keep the negative word in mind.','Judge every option against that exact scope. A sentence can be true about a different practice and still be the exception here. Do not choose an option just because it sounds unfamiliar.','Read your chosen option together with the question once more. Check that you selected what does NOT fit, rather than a strong positive example.']},
 list:{title:'Several statements: judge them separately',steps:['Evaluate statement 1, then 2, then the remaining statements. Decide whether each is supported before looking for an answer pair.','Pay attention to limits such as all, only, always and must. These words are not automatically wrong, but the statement must justify the restriction.','Match your supported statements to one of the four answer choices. Select the whole pair, not just the option containing one statement you recognise.']},
 purpose:{title:'PRIMARY / MAIN / PURPOSE: why does it exist?',steps:['Name the thing being asked about: a practice, a role or the service itself. Then ask what it is mainly intended to achieve.','Separate its purpose from a task, a tool and a useful side effect. Something a practice sometimes does is not necessarily why the practice exists.','Compare the closest two answers by their main outcome. Choose the one describing the stated purpose, not the most detailed or technically impressive sentence.']},
 best:{title:'BEST / MOST: choose the closest fit',steps:['Identify exactly what needs explaining or deciding. Use the facts in the question; do not add an outage, approval rule or other detail that is not stated.','Read all four options. More than one can sound reasonable, but they can describe different responsibilities, stages or outcomes.','Choose the option most directly supported by the question and the ITIL concept. Being partly true, being longer or sounding more cautious is not enough.']},
 role:{title:'ROLE / RESPONSIBILITY: who is accountable?',steps:['Look for the action or responsibility, rather than a person’s job title. A director is not automatically the customer or sponsor in every situation.','Separate defining requirements, authorising funding and using a service. Also distinguish who authorises a change from who implements it.','Match the described responsibility to the role. One person can perform more than one role, but the question asks which role is being performed here.']},
 first:{title:'FIRST / NEXT: locate the current stage',steps:['Identify what has already been done and what information is still missing. Do not start the whole process again if an earlier step is already complete.','Distinguish understanding the situation, choosing a target, planning action, acting and checking results. A useful later action is not automatically the next action.','Choose the next step justified by the situation. Do not assume every service value chain activity follows a fixed linear order.']},
 missing:{title:'Missing word: complete the meaning',steps:['Read the entire sentence, not just the words next to the blank. Identify the precise idea being defined.','Try each candidate in the gap. The completed sentence must fit the ITIL meaning, not merely be grammatically possible.','Check the nearest competing concept. For example, providing needed functionality and assuring agreed conditions of use describe different things.']},
 standard:{title:'Definition / characteristic: be precise',steps:['Rephrase the question in one short sentence: what is being defined, or which characteristic is required?','Read each answer completely. Similar words can describe a purpose, an activity, a role or a result; those are not interchangeable.','Compare the closest alternatives and identify the decisive difference. Use that difference to justify your answer in your own words.']}
};
const guides={
 roles:['Requirements, funding and use are different responsibilities. Customer: requirements and consumption outcomes. Sponsor: budget authorisation. User: actual use. One person can hold several roles.','A department head specifies what a booking service must achieve; finance authorises its budget; employees book rooms. Match the action, not the seniority.','Could I explain why the other consumer role is not the one described?'],
 utility:['Utility is the needed functionality: fit for purpose. Warranty is assurance of agreed conditions of use: fit for use. Output is a deliverable; outcome is the result it enables for a stakeholder.','A booking tool can reserve a room (utility), meets agreed availability (warranty), produces a confirmation (output), and helps staff avoid room conflicts (outcome).','Am I judging what the service does, how reliably it can be used, what was delivered, or the result for someone?'],
 value:['Value is perceived benefit, usefulness and importance. An output is a deliverable, not proof of an outcome. A service can remove some costs and risks while introducing others.','A hosted system removes the need to operate servers but introduces subscription costs and supplier dependency. Value depends on the consumer’s overall experience and results.','Have I confused a delivered thing with an achieved result, or assumed all costs and risks disappear?'],
 service:['Service management describes organisational capabilities for enabling value through services. A service enables desired outcomes without the consumer managing specific costs and risks. An offering describes services for a target consumer group.','Managed email is a service. A package describing mailbox access, support and account setup is a service offering. Managing the people, tools and ways of working involves service management capabilities.','Does the option describe the capability, the service arrangement, or the description of what is offered?'],
 principles:['Guiding principles are recommendations used together, not isolated steps. Start where you are means assess and reuse what works. Progress iteratively means manageable steps with feedback. Optimize and automate means improve work before automating appropriate parts.','Before replacing a support process, observe how it works. Improve a small part, get feedback and remove unnecessary work before choosing what to automate. Several principles can help; the question’s emphasis decides the best answer.','What decision in this question points most directly to the named principle?'],
 dimensions:['The four dimensions are complementary views: organisations and people; information and technology; partners and suppliers; value streams and processes. A real issue can affect several dimensions.','Lack of staff skills mainly points to people; unreliable data to information; sourcing contracts to suppliers; and poorly coordinated activities to value streams and processes.','Which dimension is most directly indicated, rather than merely affected as a consequence?'],
 svs:['The service value system brings together guiding principles, governance, the service value chain, practices and continual improvement. It explains how an organisation’s components and activities work together to enable value.','Governance evaluates, directs and monitors. The value chain is the operating model within the wider system. A practice is not another name for the entire value system.','Am I confusing the whole system with one component inside it?'],
 chain:['The value chain activities are Plan, Improve, Engage, Design and transition, Obtain/build, and Deliver and support. A value stream combines activities to meet a particular need; the chain is not a fixed six-step sequence.','Engage understands stakeholder needs; Design and transition shapes services to meet expectations; Obtain/build ensures components are available; Deliver and support operates and supports the service. Plan aligns direction; Improve develops improvements.','What is the immediate purpose of the activity, and what is its output used for?'],
 security:['Information security management protects the information needed to conduct business, including confidentiality, integrity and availability. Security is broader than secrecy, passwords or blocking every change.','Keeping records accessible to authorised staff addresses availability. Preventing unauthorised alteration addresses integrity. Limiting disclosure addresses confidentiality.','Which information property is at issue, and is the answer broader than one security tool?'],
 relations:['Relationship management builds and maintains stakeholder relationships. Supplier management ensures suppliers and their performance support quality services. Service level management sets business-based service targets and assesses and improves delivery.','A strategic discussion about a customer’s changing needs concerns the relationship. Reviewing a supplier’s delivery concerns suppliers. Agreeing a measurable service target concerns service level management.','Is this about the stakeholder relationship, supplier performance or an agreed service level?'],
 assets:['IT asset management manages the asset lifecycle to maximise value and control costs and risks. Service configuration management provides accurate configuration information, including configuration items and their relationships.','Knowing a licence’s cost and expiry supports asset management. Knowing which database supports a service helps configuration-based impact analysis. A component can be both an asset and a configuration item.','Does the question emphasise financial/lifecycle control or reliable configuration and relationship information?'],
 events:['An event is a significant state change relevant to managing a service or configuration item. Monitoring and event management observes and records these changes. An incident is a service interruption or reduction in quality; not every event is an incident.','A utilisation threshold can generate an event before service quality is affected. If users cannot complete transactions, there may also be an incident needing restoration.','Is the question about detecting a change of state or restoring affected service?'],
 release:['Change enablement assesses risk, authorises changes and manages the change schedule. Deployment moves components to an environment. Release makes new or changed services or features available for use.','Code can be deployed while a feature stays switched off. Making that feature available later is a release decision. Authorising the change is a separate responsibility.','Am I identifying authorisation, movement to an environment, or availability for use?'],
 changes:['A standard change is low-risk, understood, documented and pre-authorised under an agreed model. A normal change needs assessment, scheduling and authorisation appropriate to it. An emergency change is expedited, not automatically uncontrolled.','Routine work following an approved model can be standard. Calling an unfamiliar change urgent does not make it pre-authorised. The appropriate change authority depends on the change.','Is there an approved model, what risk exists, and who is authorised to decide?'],
 incidents:['Incident management restores normal service quickly to minimise negative impact. Problem management reduces the likelihood and impact of incidents by managing causes, workarounds and known errors. Service restoration need not wait for a permanent fix. Prioritisation considers impact and urgency.','Restarting a failed worker can restore service. Investigating why it keeps failing belongs to problem work. The incident can be resolved while the underlying problem remains open.','Is the immediate goal restoring service or understanding and reducing the cause?'],
 problems:['A problem is an actual or potential cause of incidents. A known error is an analysed but unresolved problem. A workaround reduces impact without fully resolving the cause; a documented workaround is not required for every known error.','A defect may be understood but too expensive to fix immediately. Its known-error information can support future incident diagnosis while risks and workarounds are managed.','Have I assumed an analysed problem is resolved, or that every known error must have a workaround?'],
 requests:['Service request management handles predefined, user-initiated requests as part of normal service delivery. The service desk is the entry/contact point, not the practice that personally performs every specialist fulfilment task.','A user requests agreed software access through the desk. A predefined fulfilment workflow may check entitlement and obtain approval before granting access. Routine does not mean approval is never needed.','Is this the contact point, the fulfilment practice, or an interruption that should be treated as an incident?'],
 desk:['The service desk captures demand for incident resolution and service requests and provides the central contact point for users. Understanding, empathy and communication matter; specialist teams may perform the technical resolution.','A user reports an application failure. The desk captures useful information, communicates and coordinates. A specialist repairs the issue without making the desk’s contact role unnecessary.','Have I mistaken being the contact point for personally resolving every technical issue?'],
 levels:['Service level management sets clear, business-based service targets and assesses, monitors and manages delivery against them. Measures should reflect the whole service and user experience, not only component counters.','Every server dashboard can be green while users cannot finish a transaction on time. End-to-end service measures and user feedback reveal what component-only measures miss.','Does this measure reflect a meaningful service outcome agreed with the business?'],
 improvement:['The continual improvement model separates vision, baseline, target, plan, action, evaluation and keeping momentum. The next step depends on where the organisation is now; improvement is everyone’s responsibility.','Where are we now establishes a baseline. Where do we want to be defines targets. How do we get there plans work. Take action carries it out; Did we get there compares results with targets.','Am I defining the destination, planning the route, executing it or evaluating the result?']
};
function strategy(q){const p=q.prompt.toUpperCase();const key=/\bNOT\b|\bEXCEPT\b/.test(p)?'negative':/\bTWO\b|\bTHREE\b/.test(p)&&(/\n\s*1\./.test(p)||q.kind==='list')?'list':/\bPRIMARY\b|\bMAIN\b|\bPURPOSE\b/.test(p)?'purpose':/\bFIRST\b|\bNEXT\b/.test(p)?'first':/\bROLE\b|\bRESPONSIB/.test(p)?'role':q.kind==='missing-word'||p.includes('[?]')?'missing':/\bBEST\b|\bMOST\b/.test(p)?'best':'standard';return strategies[key]}
function guide(q){const t=(q.tag||'').toLowerCase();let k;if(Number(q.lo)===2)k='principles';else if(Number(q.lo)===3)k='dimensions';else if(Number(q.lo)===4)k='svs';else if(Number(q.lo)===5)k='chain';else if(/utility|warranty/.test(t))k='utility';else if(/customer|sponsor|consumer roles/.test(t))k='roles';else if(/cost|risk|output|outcome|co-creation|^value$/.test(t))k='value';else if(Number(q.lo)===1)k='service';else if(/improv|baseline|vision|momentum/.test(t))k='improvement';else if(/asset|configuration|\bci\b/.test(t))k='assets';else if(/security/.test(t))k='security';else if(/release|deployment/.test(t))k='release';else if(/change/.test(t)&&!/requests/.test(t))k='changes';else if(/level|measures|agreements/.test(t))k='levels';else if(/relationship|supplier/.test(t))k='relations';else if(/monitor|event/.test(t))k='events';else if(/request/.test(t))k='requests';else if(/desk/.test(t))k='desk';else if(/incident/.test(t))k='incidents';else k='problems';const [distinction,example,selfCheck]=guides[k];return{distinction,example,selfCheck}}
window.FocusHelp=Object.freeze({strategy,guide});
})();
