(()=>{'use strict';
const app=document.getElementById('app');
const DATA=window.SQ_TRAINING_DATA;
const PASS=26,SECONDS=60*60;
const blueprint={'1.1':2,'1.2':2,'1.3':1,'2.1':1,'2.2':5,'3.1':2,'4.1':1,'5.1':1,'5.2':1,'6.1':5,'6.2':2,'7.1':17};
const labels={'1.1':'Key concepts','1.2':'Service relationships','1.3':'Utility / warranty','2.1':'Guiding principles purpose','2.2':'Guiding principles','3.1':'Four dimensions','4.1':'Service value system','5.1':'Service value chain purpose','5.2':'Value chain activities','6.1':'15 practices: purpose & terms','6.2':'Practice definitions','7.1':'7 practices in detail'};
let exam=null,timer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mix=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function officialLikeScore(q){const p=(q.prompt||'').toUpperCase();let n=0;[' BEST ',' NOT ',' MOST ',' PRIMARY ',' MAIN ',' WHICH ',' WHAT IS ',' PURPOSE ',' ROLE ',' CHARACTERISTIC '].forEach(k=>{if((' '+p+' ').includes(k))n+=2});if((q.kind||'').toLowerCase().includes('scenario'))n+=2;if((q.whyNl||'').length>80)n++;return n+Math.random();}
function makePaper(){const strict=DATA?.strictQuestions||[];const out=[];for(const [crit,count] of Object.entries(blueprint)){const pool=strict.filter(q=>String(q.criterion)===crit).sort((a,b)=>officialLikeScore(b)-officialLikeScore(a));if(pool.length<count)throw new Error('Niet genoeg vragen voor '+crit);out.push(...pool.slice(0,count));}return mix(out).map(q=>({q,order:mix([0,1,2,3]),choice:null,checked:false}));}
function fmt(s){const m=Math.max(0,s),min=Math.floor(m/60),sec=m%60;return String(min).padStart(2,'0')+':'+String(sec).padStart(2,'0')}
function stopTimer(){if(timer){clearInterval(timer);timer=null}}
function startTimer(){stopTimer();timer=setInterval(()=>{if(!exam)return;exam.left--;const el=document.querySelector('.timer');if(el){el.textContent=fmt(exam.left);el.classList.toggle('danger',exam.left<=300)}if(exam.left<=0){stopTimer();finish(true)}},1000)}
function startScreen(){stopTimer();app.innerHTML=`<section class="card start"><span class="eyebrow">SERVICE QUEST · MOCK ONLY</span><h1>ITIL 4 Foundation<br>Mock Exam</h1><p>Alle andere spelonderdelen zijn uit deze versie gehaald. Je krijgt alleen examengerichte multiple-choicevragen in het Engels, met Nederlandse uitleg nadat je antwoordt.</p><div class="facts"><div class="fact"><b>40</b><span>vragen</span></div><div class="fact"><b>60 min</b><span>examenduur</span></div><div class="fact"><b>26 / 40</b><span>slaaggrens</span></div><div class="fact"><b>157</b><span>curated contrastvragen</span></div></div><button class="btn primary" id="start">Start nieuw mock examen</button><p class="notice">De vragen zijn eigen oefenvragen en geen gekopieerde PeopleCert-examenvragen. De selectie volgt de ITIL 4 Foundation-verdeling die we voor deze bank gebruiken. Na ieder antwoord krijg je uitleg en een onthoudtip; daardoor is dit vooral bedoeld om te leren, niet als zuivere eindmeting.</p></section>`;document.getElementById('start').onclick=startExam}
function startExam(){try{exam={items:makePaper(),index:0,score:0,left:SECONDS,finished:false,byTopic:{}};startTimer();render()}catch(e){app.innerHTML=`<section class="card"><h1>Kon mock niet starten</h1><p>${esc(e.message)}</p></section>`}}
function readingTip(prompt){const p=String(prompt||'').toUpperCase();if(/\bNOT\b/.test(p))return '<b>Leesstrategie:</b> NOT-vraag → zoek eerst de drie antwoorden die wél kloppen. Het overblijvende antwoord is je kandidaat.';if(/\bBEST\b|\bMOST\b/.test(p))return '<b>Leesstrategie:</b> BEST/MOST → meerdere antwoorden kunnen deels waar zijn. Kies degene die het meest direct past bij de ITIL-definitie of het doel.';if(/\bPRIMARY\b|\bMAIN\b/.test(p))return '<b>Leesstrategie:</b> PRIMARY/MAIN → zoek het hoofddoel, niet een nuttig neveneffect.';if(/\bPURPOSE\b/.test(p))return '<b>Leesstrategie:</b> purpose-vraag → denk: “waarom bestaat deze practice?” en niet “welke activiteit kan erbij horen?”';if(/\bROLE\b|\bRESPONSIB/.test(p))return '<b>Leesstrategie:</b> rol-vraag → onderscheid verantwoordelijkheid van een losse taak of activiteit.';return '<b>Leesstrategie:</b> bepaal eerst welk ITIL-begrip de vraag test en vergelijk daarna pas de antwoordopties.'}
function render(){const it=exam.items[exam.index],q=it.q;const pct=Math.round(exam.index/40*100);app.innerHTML=`<section class="card"><div class="top"><div><div class="brand">ITIL 4 · MOCK</div><div class="meta">Vraag ${exam.index+1} van 40</div></div><div class="timer ${exam.left<=300?'danger':''}">${fmt(exam.left)}</div></div><div class="progress"><i style="width:${pct}%"></i></div><span class="eyebrow">Exam-style · English</span><h1 class="question" lang="en">${esc(q.prompt)}</h1><div class="options" lang="en">${it.order.map((idx,pos)=>{const cls=it.checked?(idx===0?' good':idx===it.choice?' bad':''):it.choice===idx?' selected':'';return `<button class="option${cls}" data-choice="${idx}" ${it.checked?'disabled':''}><strong>${'ABCD'[pos]}</strong><span>${esc(q.options[idx])}</span></button>`}).join('')}</div><div class="actions"><button class="btn primary" id="check" ${it.choice===null||it.checked?'disabled':''}>Controleer antwoord</button></div>${it.checked?feedback(it):''}</section>`;
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(it.checked)return;it.choice=Number(b.dataset.choice);render()});
 const check=document.getElementById('check');if(check)check.onclick=checkAnswer;
 const next=document.getElementById('next');if(next)next.onclick=nextQuestion;
}
function feedback(it){const q=it.q,right=it.choice===0;const chosen=q.options[it.choice];return `<section class="feedback ${right?'':'wrong'}"><h3 class="${right?'correct':'wrongtext'}">${right?'✓ Correct':'✕ Niet correct'}</h3>${!right?`<p class="wrongtext"><b>Jouw antwoord:</b> ${esc(chosen)}</p>`:''}<p class="correct"><b>Juiste antwoord:</b> ${esc(q.options[0])}</p>${q.why?`<p lang="en">${esc(q.why)}</p>`:''}${q.whyNl?`<p lang="nl"><b>Waarom:</b> ${esc(q.whyNl)}</p>`:''}<div class="tip" lang="nl">${readingTip(q.prompt)}</div>${q.hook?`<div class="tip" lang="nl"><b>Onthoud:</b> ${esc(q.hook)}</div>`:''}<div class="actions"><button class="btn primary" id="next">${exam.index===39?'Bekijk resultaat':'Volgende vraag'}</button></div></section>`}
function checkAnswer(){const it=exam.items[exam.index];if(it.choice===null||it.checked)return;it.checked=true;const right=it.choice===0;if(right)exam.score++;const crit=String(it.q.criterion||'overig');exam.byTopic[crit]??={right:0,total:0};exam.byTopic[crit].total++;if(right)exam.byTopic[crit].right++;render();document.querySelector('.feedback')?.scrollIntoView({behavior:'smooth',block:'start'})}
function nextQuestion(){if(exam.index===39){finish(false);return}exam.index++;render();window.scrollTo({top:0,behavior:'smooth'})}
function finish(timeout){stopTimer();exam.finished=true;const answered=exam.items.filter(i=>i.checked).length;const score=exam.score;const pass=score>=PASS;const topics=Object.entries(exam.byTopic).sort((a,b)=>{const pa=a[1].right/a[1].total,pb=b[1].right/b[1].total;return pa-pb}).map(([c,s])=>`<div class="topic"><div><b>${esc(labels[c]||c)}</b><br><small>${esc(c)}</small></div><strong>${s.right}/${s.total}</strong></div>`).join('');app.innerHTML=`<section class="card results"><span class="eyebrow">MOCK RESULT</span><h1>${pass?'Geslaagd op deze oefenset':'Nog niet op de oefenslaaggrens'}</h1><div class="score ${pass?'pass':'fail'}">${score}/40</div><p>${Math.round(score/40*100)}% · ${answered} vragen gecontroleerd${timeout?' · tijd verstreken':''}</p><p>${pass?'Je zit boven 26/40. Blijf vooral de verschillen tussen vergelijkbare practices oefenen.':'Je hebt '+Math.max(0,PASS-score)+' extra punten nodig om 26/40 te halen. Pak eerst de zwakste onderwerpen hieronder.'}</p><h2>Onderwerpen van zwak naar sterk</h2><div class="topic-list">${topics||'<p>Geen antwoorden gecontroleerd.</p>'}</div><div class="actions"><button class="btn primary" id="again">Nieuw mock examen</button></div><p class="notice">Deze score is oefenfeedback en geen garantie voor het echte PeopleCert-examen.</p></section>`;document.getElementById('again').onclick=startExam}
if(!DATA||!Array.isArray(DATA.strictQuestions)||DATA.strictQuestions.length<40){app.innerHTML='<section class="card"><h1>Vragenbank niet beschikbaar</h1><p>Ververs de pagina. Als dit blijft gebeuren, moet de live build worden hersteld.</p></section>'}else startScreen();
})();
